version: '3'
services:
    ec2_collector:
        container_name: ec2_collector
        build: .
        environment:
          - AWS_ACCESS_KEY_ID=$AWS_KEY
          - AWS_SECRET_ACCESS_KEY=$AWS_SECRET
          - AWS_DEFAULT_REGION=us-west-2
        volumes:
          - "EC2data:/usr/src/app"
        links:
          - mongodb
        depends_on:
          - mongodb
    web:
        container_name: nginx
        image: nginx:latest
        ports:
          - "8088:80"
        volumes:
          - "EC2data:/usr/share/nginx/html:ro"
    mongodb:
        container_name: "mongodb"
        image: mongo:4
        restart: always
        environment:
          - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
          - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASS
        ports:
          - "27017:27017"
        command: --auth
volumes:
    EC2data:
